wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663720085.714797
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 40
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 40
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.2
      6: 4.22.1
      8:
      - 5
batch_size:
  desc: null
  value: 128
checkpoint:
  desc: null
  value: false
checkpoint_path:
  desc: null
  value: null
classifier_lr:
  desc: null
  value: 0.1
classifier_weight_decacy:
  desc: null
  value: 0
data_path:
  desc: null
  value: ../../../data/
dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0.4
    contrast: 0.4
    crop_size: 224
    gaussian_prob: 0.5
    gray_scale_prob: 0.2
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 0.95
    min_scale: 0.6
    root: ../../../data/
    saturation: 0.2
dist_url:
  desc: null
  value: env://
epochs:
  desc: null
  value: 0
gpu_id:
  desc: null
  value: 0
job_id:
  desc: null
  value: 0
log:
  desc: null
  value: true
log_n_steps:
  desc: null
  value: 100
log_n_train_steps:
  desc: null
  value: 100
log_n_val_steps:
  desc: null
  value: 69
lr:
  desc: null
  value: 0.001
name:
  desc: null
  value: CLIP_image
rank:
  desc: null
  value: 0
steps:
  desc: null
  value: 801
val_dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0
    contrast: 0.4
    crop_size: 224
    gaussian_prob: 0
    gray_scale_prob: 0
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1
    min_scale: 0.9
    root: ../../../data/
    saturation: 0.2
val_steps:
  desc: null
  value: 70
warmup_steps:
  desc: null
  value: 200
wd:
  desc: null
  value: 1.5e-06
workers:
  desc: null
  value: 6
world_size:
  desc: null
  value: 1
