wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1663763312.556868
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 40
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 40
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.13.2
      6: 4.22.1
      8:
      - 5
batch_size:
  desc: null
  value: 256
data_path:
  desc: null
  value: ../../../data/
dist_url:
  desc: null
  value: env://
gpu_id:
  desc: null
  value: 0
job_id:
  desc: null
  value: 0
log:
  desc: null
  value: true
log_n_train_steps:
  desc: null
  value: 100
log_n_val_steps:
  desc: null
  value: 49
name:
  desc: null
  value: Eval_Clip_image
rank:
  desc: null
  value: 0
saved_path:
  desc: null
  value: checkpoints/CLIP_image/CLIP_image_Final.pt
val_dataset_args:
  desc: null
  value:
    brightness: 0.4
    color_jitter_prob: 0
    contrast: 0.4
    crop_size: 224
    gaussian_prob: 0
    gray_scale_prob: 0
    horizontal_flip_prob: 0.5
    hue: 0.1
    max_scale: 1
    min_scale: 0.9
    root: ../../../data/
    saturation: 0.2
val_steps:
  desc: null
  value: 50
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
